# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-13 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_activity_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='ac_name',
            new_name='Activityname',
        ),
    ]
