# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170314_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
