# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='Allergies',
        ),
        migrations.AddField(
            model_name='medication',
            name='days',
            field=models.BigIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=1, verbose_name='Allergies:'),
            preserve_default=False,
        ),
    ]
