# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20170314_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='day',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='vote',
            name='days',
            field=models.BigIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=0, verbose_name='Allergies:'),
            preserve_default=False,
        ),
    ]
