# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='days',
            field=models.CharField(max_length=50),
        ),
    ]
